### ISSUE TITLE
Long wait time to fetch constants.json from heroku

### ISSUE THREAD

**Issue by smyaknti** [SharpBit/brawlstats#40]
### The Issue
In [this line](https://github.com/SharpBit/brawlstats/blob/351b9b7009dff9e1e36bd52ae509d1b7c1ed72de/brawlstats/officialapi/utils.py#L24), the program waits a while to connect and fetch the 5 MB `constants.json` file. Its fine for servers but can be a pain for slow connections.

### Suggested Modifications
Maybe some way to locally cache the file in the running directory of the script would definitely help.
I understand that it only runs once per the initialisation of the client object but a local cache of the file would be a nice thing to have. (_Assuming its updated once per month?_)

**Comment by SharpBit** [comment]
Yes, the purpose of the MANIFEST.in file is supposed to include these when installing the package, however it seems like it is not installed locally

**Comment by SharpBit** [comment]
Workaround: Request the `/characters` endpoint to significantly reduce the size of the json file

**Comment by smyaknti** [comment]
> Workaround: Request the `/characters` endpoint to significantly reduce the size of the json file

Why not **only call for the JSON data when the `BRAWLERS` attribute is required** just to speed it up. No need to call when initialising the client.
For the official API, I think its required only in the `client.get_rankings` function. So for someone only tracking an individual's progress, it is not needed? Or I may have missed some important dependency of it.

**Comment by SharpBit** [comment]
Wow, this is an old issue. A problem that occured is that since this wrapper uses 1 client for both async and sync usage, we can't run the coroutine `_aget_model` inside of the sync function `get_rankings`. Any attempts for `loop.run_until_complete` do not work since the event loop is already running. See the development branch for the current implementation (fetched when client is initialized). Regular user usage works, you can test it on `examples/async.py` and it will work, but it fails in tox tests and will say that the event loop is already running,

**Comment by SharpBit** [comment]
Fixed in v4.0.4
