### ISSUE TITLE
Surge is invalid brawler

### ISSUE THREAD

**Issue by appleGun22** [SharpBit/brawlstats#66]
Can you make an update where surge is an existing brawler?

**Comment by SharpBit** [comment]
In version 4.0.3 of brawlstats, it checks to make sure the entered brawler is valid by requesting from https://fourjr.herokuapp.com/bs/constants/characters, which is the same as https://github.com/fourjr/bs-data. I have contacted 4jr to update the repo for the latest update. There is no fix for now, unless you want to try the development branch, which requests from the official supercell API for brawlers. To install, you can type `pip install -U git+https://github.com/SharpBit/brawlstats@development`. However, there may still be bugs with the development branch since it's not stable, but if you really want to get surge stats immediately, you can try installing that.

**Comment by SharpBit** [comment]
If this hasnt been fixed already, you can always download v4.0.4 and it will be fixed.
